name: Cargo Build

on:
    workflow_dispatch:
    push:
        branches: main
        paths-ignore:
            - .gitignore
            - Readme.md
    pull_request:
        branches: main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              name: Checkout
              with:
                  submodules: true
                  lfs: true

            - name: Cargo build
              run: |
                  cd ${GITHUB_WORKSPACE}    
                  cargo build
            - name: Upload executable
              uses: actions/upload-artifact@v2
              with:
                name: qpm-rust
                path: ./target/debug/qpm-rust
                # if not found error obviously
                if-no-files-found: error
