name: Cargo Build

on:
    workflow_dispatch:
    push:
        branches: main
        paths-ignore:
            - .gitignore
            - Readme.md
    pull_request:
        branches: main

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                targetOS: [ubuntu-latest, windows-latest, macOS-latest]
                include:
                    - targetOS: ubuntu-latest
                      os: ubuntu-latest
                      file-name: "qpm-rust"
                      finalPrefix: ubuntu-latest
                      build-folder: "./target/debug/"

                    - targetOS: macOS-latest
                      os: macOS-latest
                      file-name: "qpm-rust"
                      finalPrefix: macOS-latest
                      build-folder: "./target/debug/"

                    - targetOS: windows-latest
                      os: windows-latest
                      file-name: "qpm-rust.exe"
                      finalPrefix: windows-latest
                      build-folder: "./target/debug/"
        steps:
            - uses: actions/checkout@v2
              name: Checkout
              with:
                  submodules: true
                  lfs: true

            - uses: actions-rs/toolchain@v1

            - uses: actions/cache@v2
              with:
                path: |
                  ~/.cargo/bin/
                  ~/.cargo/registry/index/
                  ~/.cargo/registry/cache/
                  ~/.cargo/git/db/
                  target/
                key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

            - name: Get libdbus if ubuntu-latest
              if: ${{ matrix.os == 'ubuntu-latest' }}
              run: |
                sudo apt-get install -y libdbus-1-dev

            - name: Cargo build
              run: |
                  cargo build --verbose
                
            - name: Upload executable
              uses: actions/upload-artifact@v2
              with:
                name: ${{matrix.finalPrefix}}-${{matrix.file-name}}
                path: ${{matrix.build-folder}}${{matrix.file-name}}
                if-no-files-found: error
